services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    restart: always

  streamlit:
    image: python:3.11-slim
    container_name: streamlit
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - PLC_HOST=host.docker.internal
    command: >
      bash -c "pip install streamlit pandas pymodbus==2.5.3 requests influxdb-client python-dotenv reportlab &&
               streamlit run streamlit_app/app.py --server.port=8501 --server.address=0.0.0.0"
    ports:
      - "8501:8501"
    restart: always

  attacker:
    image: python:3.11-slim
    container_name: attacker
    working_dir: /app
    volumes:
      - ./attacks:/app
    command: >
      bash -c "pip install pymodbus==2.5.3 &&
               tail -f /dev/null"
    restart: always

volumes:
  influxdb_data: